version: '3'

networks:
  builders:

services:
  app:
    image: marioj95/builders:latest
    container_name: customers-api
    ports:
      - 8080:8080
    networks:
      - builders
  redis:
    image: redis
    container_name: bredis
    networks:
      - builders
    ports:
      - 6379:6379